Make sure cfv is installed first

diff --git a/gitbackup b/gitbackup
--- a/gitbackup
+++ b/gitbackup
@@ -15,6 +15,11 @@ if [[ ${#REPOS[@]} -lt 1 ]]; then
     exit 1
 fi
 
+# Make sure that cfv is installed.
+command -v cfv >/dev/null 2>&1 || { \
+    echo >&2 "Cfv is not installed. Aborting!"; exit 1; \
+}
+
 for repo_url in "${REPOS[@]}"; do
     filename=$(basename $repo_url)
     repo="${filename%.*}"
