Ensure the s3cmd is installed and configured

diff --git a/gitbackup b/gitbackup
--- a/gitbackup
+++ b/gitbackup
@@ -20,6 +20,17 @@ command -v cfv >/dev/null 2>&1 || { \
     echo >&2 "Cfv is not installed. Aborting!"; exit 1; \
 }
 
+# Make sure s3cmd is installed.
+command -v s3cmd >/dev/null 2>&1 || { \
+    echo >&2 "S3cmd is not installed. Aborting!"; exit 1; \
+}
+
+# Make sure s3cmd has been configured.
+if [ ! -f ~/.s3cfg ]; then
+    echo >&2 "S3cmd has not been configured yet. Aborting!"
+    exit 1
+fi
+
 for repo_url in "${REPOS[@]}"; do
     filename=$(basename $repo_url)
     repo="${filename%.*}"
